// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrchidLLM.Web.Data;

#nullable disable

namespace OrchidLLM.Web.Migrations
{
    [DbContext(typeof(OrchidDbContext))]
    partial class OrchidDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.AdminNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReadBy")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ReadBy");

                    b.ToTable("AdminNotifications");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.AdminSqlQueryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminUserId")
                        .HasColumnType("int");

                    b.Property<bool>("DestructiveOverride")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.ToTable("AdminSqlQueryLogs");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BannerExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBanner")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("RelatedAnnouncementId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("VersionTag")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RelatedAnnouncementId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreditLimitDaily")
                        .HasColumnType("int");

                    b.Property<string>("CreditLimitReset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("CreditLimitTotal")
                        .HasColumnType("int");

                    b.Property<int>("CreditUsedToday")
                        .HasColumnType("int");

                    b.Property<int>("CreditUsedTotal")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("ExposeBalance")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("KeyPreview")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ModelWhitelist")
                        .HasColumnType("json");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.BatchRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualCreditsCharged")
                        .HasColumnType("int");

                    b.Property<int?>("ApiKeyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("DiscountRate")
                        .HasColumnType("double");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderBatchJobId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("QueuePriority")
                        .HasColumnType("int");

                    b.Property<int>("ReservedCredits")
                        .HasColumnType("int");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BatchRequests");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.BoosterPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AvailableFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("AvailableUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BadgeText")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContextUnlockTiers")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreditsFast")
                        .HasColumnType("int");

                    b.Property<int>("CreditsStandard")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("EligibleTiers")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("GradientEnd")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("GradientStart")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<bool>("IgnorePlanLock")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxPurchasesPerUser")
                        .HasColumnType("int");

                    b.Property<int>("MaxTotalPurchases")
                        .HasColumnType("int");

                    b.Property<string>("ModelAccessTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PermanentBaseTierId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceIdr")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("PriceUsd")
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("QueuePriorityFast")
                        .HasColumnType("int");

                    b.Property<int>("QueuePriorityStandard")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermanentBaseTierId");

                    b.ToTable("BoosterPacks");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.BoosterPackTargetingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LogicGroup")
                        .HasColumnType("int");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("PackId")
                        .HasColumnType("int");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("TimeframeEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("TimeframeStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TimeframeType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<double>("ValueA")
                        .HasColumnType("double");

                    b.Property<double?>("ValueB")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("PackId");

                    b.ToTable("BoosterPackTargetingRules");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.BoosterPackWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContextUnlockTiers")
                        .HasColumnType("json");

                    b.Property<int>("CreditsAmount")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ModelAccessTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("PackId")
                        .HasColumnType("int");

                    b.Property<int>("QueuePriority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackId");

                    b.ToTable("BoosterPackWallets");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.DemoKey", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("LastRequestDay")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("RequestsToday")
                        .HasColumnType("int");

                    b.Property<int>("TotalRequests")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DemoKeys");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessTier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ContextWindowTiers")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeprecationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxOutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("ModelMakerId")
                        .HasColumnType("int");

                    b.Property<string>("ModelSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PublicDescription")
                        .HasColumnType("longtext");

                    b.Property<bool>("SupportsCaching")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsFunctionCalling")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsReasoning")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsSearch")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsVision")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ModelMakerId");

                    b.HasIndex("ModelSlug")
                        .IsUnique();

                    b.ToTable("Models");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.ModelMaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ModelMakers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "OpenAI",
                            Slug = "openai",
                            SortOrder = 10,
                            UpdatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Anthropic",
                            Slug = "anthropic",
                            SortOrder = 20,
                            UpdatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Google",
                            Slug = "google",
                            SortOrder = 30,
                            UpdatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Meta",
                            Slug = "meta",
                            SortOrder = 40,
                            UpdatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Mistral AI",
                            Slug = "mistral-ai",
                            SortOrder = 50,
                            UpdatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.ModelProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContextLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxConcurrent")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderModelId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("RateLimitUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SpeedPriority")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SupportsParams")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ModelId", "ProviderId")
                        .IsUnique();

                    b.ToTable("ModelProviders");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.ModelTokenMultiplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ContextTierMax")
                        .HasColumnType("int");

                    b.Property<int>("ContextTierMin")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<double>("MultiplierCacheRead")
                        .HasColumnType("double");

                    b.Property<double>("MultiplierCacheWrite")
                        .HasColumnType("double");

                    b.Property<double>("MultiplierInput")
                        .HasColumnType("double");

                    b.Property<double>("MultiplierOutput")
                        .HasColumnType("double");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("ModelTokenMultipliers");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnvKeyPrefix")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ErrorAliasOverrides")
                        .HasColumnType("json");

                    b.Property<bool>("Free")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxConcurrent")
                        .HasColumnType("int");

                    b.Property<string>("Modalities")
                        .HasColumnType("json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RateLimitUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RpmCap")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.ReferralTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditReward")
                        .HasColumnType("int");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PurchaseId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ReferredUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReferrerUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReferredUserId");

                    b.HasIndex("ReferrerUserId");

                    b.ToTable("ReferralTransactions");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.RequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApiKeyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreditsCharged")
                        .HasColumnType("int");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.RequestQueueItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("ActualCredits")
                        .HasColumnType("int");

                    b.Property<int?>("ApiKeyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("PayloadRef")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("int");

                    b.Property<int>("ReservedCredits")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Status", "Priority", "CreatedAt");

                    b.ToTable("RequestQueueItems");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.RoutingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FinalProviderId")
                        .HasColumnType("int");

                    b.Property<string>("KeyRefHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ParamsStripped")
                        .HasColumnType("json");

                    b.Property<string>("ProvidersAttempted")
                        .HasColumnType("json");

                    b.Property<int?>("QueueWaitMs")
                        .HasColumnType("int");

                    b.Property<string>("RequestId")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("RoutingReason")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("TtftMs")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("RoutingLogs");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.SubscriptionTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchQueueSlots")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreditsFastMonthly")
                        .HasColumnType("int");

                    b.Property<int>("CreditsStandardMonthly")
                        .HasColumnType("int");

                    b.Property<string>("DisplayColorToken")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("ExhaustionBatchAccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ExhaustionContextLock")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ExhaustionMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ExhaustionModelAccess")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxApiKeys")
                        .HasColumnType("int");

                    b.Property<int>("MaxConcurrentExhausted")
                        .HasColumnType("int");

                    b.Property<int>("MaxConcurrentRequests")
                        .HasColumnType("int");

                    b.Property<string>("ModelAccessTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PriceIdrMonthly")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("PriceIdrYearly")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("PriceUsdMonthly")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("PriceUsdYearly")
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("QueuePriorityExhausted")
                        .HasColumnType("int");

                    b.Property<int>("QueuePriorityFast")
                        .HasColumnType("int");

                    b.Property<int>("QueuePriorityStandard")
                        .HasColumnType("int");

                    b.Property<int>("RolloverMaxCap")
                        .HasColumnType("int");

                    b.Property<double>("RolloverPercentage")
                        .HasColumnType("double");

                    b.Property<int>("RpmExhausted")
                        .HasColumnType("int");

                    b.Property<int>("RpmNormal")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<bool>("StrictParamsOption")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsCompression")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsMonthlyBilling")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsRollover")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SupportsYearlyBilling")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SubscriptionTiers");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.SubscriptionTierBillingOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("DiscountExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("DiscountPercentage")
                        .HasColumnType("double");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TierId", "Cycle")
                        .IsUnique();

                    b.ToTable("SubscriptionTierBillingOptions");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SettingValue")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.ToTable("SystemSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Name of the default tier assigned to new users on signup",
                            IsActive = true,
                            SettingKey = "default_signup_tier",
                            SettingValue = "Free",
                            UpdatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Max demo key requests per day",
                            IsActive = true,
                            SettingKey = "demo_requests_per_day",
                            SettingValue = "20",
                            UpdatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Max context tokens for demo key users",
                            IsActive = true,
                            SettingKey = "demo_context_cap",
                            SettingValue = "33000",
                            UpdatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Description = "SSE heartbeat interval while request is queued",
                            IsActive = true,
                            SettingKey = "heartbeat_interval_seconds",
                            SettingValue = "15",
                            UpdatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Default batch request discount (0.5 = 50% off)",
                            IsActive = true,
                            SettingKey = "batch_discount_rate",
                            SettingValue = "0.5",
                            UpdatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Description = "Comma-separated GitHub usernames with admin role",
                            IsActive = true,
                            SettingKey = "admin_github_handles",
                            SettingValue = "vendouple",
                            UpdatedAt = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletionScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NotificationPrefs")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int?>("ReferredBy")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("StrictParams")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ReferralCode")
                        .IsUnique();

                    b.HasIndex("ReferredBy");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserAuthProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("UserAuthProviders");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserBoosterPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditsFastRemaining")
                        .HasColumnType("int");

                    b.Property<int>("CreditsStandardRemaining")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("InvalidatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InvalidationReason")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PackId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBoosterPacks");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserCompressionSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BasePromptLocked")
                        .HasColumnType("longtext");

                    b.Property<int?>("CompressionModelId")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("SystemPromptAppend")
                        .HasColumnType("longtext");

                    b.Property<int>("TierIndex")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompressionModelId");

                    b.HasIndex("ModelId");

                    b.HasIndex("UserId", "ModelId", "TierIndex")
                        .IsUnique();

                    b.ToTable("UserCompressionSettings");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserContextTierPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Behaviour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("TierIndex")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("UserId", "ModelId", "TierIndex")
                        .IsUnique();

                    b.ToTable("UserContextTierPreferences");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserCredit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditsFast")
                        .HasColumnType("int");

                    b.Property<int>("CreditsReserved")
                        .HasColumnType("int");

                    b.Property<int>("CreditsRollover")
                        .HasColumnType("int");

                    b.Property<int>("CreditsStandard")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCredits");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserCreditLedger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("UserCreditLedgers");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserDismissedAnnouncement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DismissedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnnouncementId");

                    b.HasIndex("UserId", "AnnouncementId")
                        .IsUnique();

                    b.ToTable("UserDismissedAnnouncements");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("CurrentPeriodEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PendingTierId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("TierId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PendingTierId");

                    b.HasIndex("TierId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.AdminNotification", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "ReadByUser")
                        .WithMany()
                        .HasForeignKey("ReadBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReadByUser");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.AdminSqlQueryLog", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.Announcement", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("OrchidLLM.Web.Data.Entities.Announcement", "RelatedAnnouncement")
                        .WithMany()
                        .HasForeignKey("RelatedAnnouncementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("RelatedAnnouncement");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.ApiKey", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.BatchRequest", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.BoosterPack", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.SubscriptionTier", "PermanentBaseTier")
                        .WithMany()
                        .HasForeignKey("PermanentBaseTierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PermanentBaseTier");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.BoosterPackTargetingRule", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.BoosterPack", "Pack")
                        .WithMany("TargetingRules")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.BoosterPackWallet", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.BoosterPack", "Pack")
                        .WithMany("Wallets")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.Model", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.ModelMaker", "ModelMaker")
                        .WithMany()
                        .HasForeignKey("ModelMakerId");

                    b.Navigation("ModelMaker");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.ModelProvider", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.Model", "Model")
                        .WithMany("Providers")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrchidLLM.Web.Data.Entities.Provider", "Provider")
                        .WithMany("ModelProviders")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.ModelTokenMultiplier", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.Model", "Model")
                        .WithMany("TokenMultipliers")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.ReferralTransaction", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "ReferredUser")
                        .WithMany()
                        .HasForeignKey("ReferredUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "ReferrerUser")
                        .WithMany()
                        .HasForeignKey("ReferrerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReferredUser");

                    b.Navigation("ReferrerUser");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.RequestLog", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.RequestQueueItem", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.RoutingLog", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.SubscriptionTierBillingOption", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.SubscriptionTier", "Tier")
                        .WithMany("BillingOptions")
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tier");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.SystemSetting", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.User", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "Referrer")
                        .WithMany()
                        .HasForeignKey("ReferredBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Referrer");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserAuthProvider", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "User")
                        .WithMany("AuthProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserBoosterPack", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.BoosterPack", "Pack")
                        .WithMany()
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pack");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserCompressionSetting", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.Model", "CompressionModel")
                        .WithMany()
                        .HasForeignKey("CompressionModelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OrchidLLM.Web.Data.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompressionModel");

                    b.Navigation("Model");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserContextTierPreference", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserCredit", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "User")
                        .WithOne("Credits")
                        .HasForeignKey("OrchidLLM.Web.Data.Entities.UserCredit", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserCreditLedger", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserDismissedAnnouncement", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.Announcement", "Announcement")
                        .WithMany()
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Announcement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.UserSubscription", b =>
                {
                    b.HasOne("OrchidLLM.Web.Data.Entities.SubscriptionTier", "PendingTier")
                        .WithMany()
                        .HasForeignKey("PendingTierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OrchidLLM.Web.Data.Entities.SubscriptionTier", "Tier")
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrchidLLM.Web.Data.Entities.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("OrchidLLM.Web.Data.Entities.UserSubscription", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PendingTier");

                    b.Navigation("Tier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.BoosterPack", b =>
                {
                    b.Navigation("TargetingRules");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.Model", b =>
                {
                    b.Navigation("Providers");

                    b.Navigation("TokenMultipliers");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.Provider", b =>
                {
                    b.Navigation("ModelProviders");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.SubscriptionTier", b =>
                {
                    b.Navigation("BillingOptions");
                });

            modelBuilder.Entity("OrchidLLM.Web.Data.Entities.User", b =>
                {
                    b.Navigation("AuthProviders");

                    b.Navigation("Credits");

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
